timholy/Revise.jl

.travis.yml, README.md
This seems to be working pretty well now. I'll give watchers a brief chance to play with it and report problems before I register this puppy.
=> Write a README

test/runtests.jl
=> pop!(LOAD_PATH) back to how it started

src/Revise.jl, test/runtests.jl
=> Add tests for path-as-Symbol

src/Revise.jl
=> Support IJulia. Fixes #9

src/Revise.jl, test/runtests.jl
=> Support docstrings for modules

src/Revise.jl, test/runtests.jl
The problem here is that multiple calls to `parse` end up discarding line information. So the strategy here is to count `'\n'` characters and keep track of how many lines we've covered.
=> Keep track of line number across multiple parse calls. Fixes #27

src/Revise.jl
Split it into two commits, since I'm not sure if the version check should be there or not with version tagging, etc.
=> Fix depwarn on latest master

src/Revise.jl, test/runtests.jl
=> module2files and a bunch of comments

src/Revise.jl
xref https://github.com/JuliaLang/julia/commit/d2041509ad94759c0fa61426f6b194473a6c8669
=> fix internal name change of JLOptions field

src/Revise.jl
Fixes #42. I can't test this locally, but hopefully this works for you @getzdan!
=> Initialization: wait until REPL backend is successfully stolen

src/Revise.jl
see https://github.com/JuliaLang/julia/pull/25102
=> JULIA_HOME -> Sys-BINDIR

REQUIRE, src/Revise.jl, src/parsing.jl, src/pkgs.jl, src/pkgs_deprecated.jl, test/runtests.jl
This incorporates #74 (this interface has changed multiple times now, and some of the nightly builds are behind).
=> Get tests passing on recent 0.7

src/Revise.jl
fix #66 
---
Basic functionality works for me, but I cannot get test passed :p
=> implement revise_file_queued for FreeBSD

README.md, REQUIRE, src/Revise.jl, src/delete_method.jl, src/parsing.jl, src/relocatable_exprs.jl, src/types.jl, test/runtests.jl
This fixes #46. This is built on top of #49 (not yet merged), so only the last commit will be in the final version of this PR.
=> Support method deletion

.travis.yml, README.md, src/Revise.jl, src/pkgs.jl, src/pkgs_deprecated.jl, test/common.jl, test/polling.jl, test/runtests.jl
Fixes #60 
Unfortunately, the new `polling.jl` tests (commented out in `.travis.yml`) don't work unless I copy/paste the statements into the REPL. I can't figure out what the problem is, and would appreciate any insights.
=> Support NFS shares with poll_file (config option)Fixes #60

src/Revise.jl
https://github.com/timholy/Revise.jl/pull/89
=> Fix Juno integration (master)

test/runtests.jl
This should help with some recent PRs.
=> Get tests passing on recent master

REQUIRE, src/Revise.jl, src/delete_method.jl, src/parsing.jl, src/pkgs.jl, test/runtests.jl
Includes #87 and fixes some more warnings
=> Fix deprecation warnings

src/delete_method.jl, test/runtests.jl
=> Support deletion when args have macros

src/Revise.jl, src/parsing.jl
=> Avoid task failures by putting errors in REPL channel

REQUIRE, src/Revise.jl, src/relocatable_exprs.jl, test/runtests.jl
=> Switch to OrderedCollections and eliminate ambiguities

REQUIRE, src/Revise.jl, test/common.jl, test/runtests.jl
https://github.com/tpapp/Revise.jl/pull/1 on top of #119
=> Support __precompile__ by default

docs/src/limitations.md, src/exprutils.jl
Ref #147 (doesn't fix it, just documents a workaround)
=> More documentation on distributed support and its limitations

src/Revise.jl, test/REQUIRE, test/runtests.jl
Fixes https://github.com/timholy/Rebugger.jl/issues/3.
=> Find method definitions even when module & file disagree

src/exprutils.jl, test/runtests.jl
=> Handle calls with empty keyword args (fixes #171)

src/parsing.jl, test/runtests.jl
We may have to expand the macro in order to get the signature, but that doesn't mean we have to store the expanded version.
=> Store unexpanded macros in defs (fixes #174)

src/Revise.jl, src/exprutils.jl, test/runtests.jl
Should fix #176. @tpapp, can you test?
=> Support argument-modifying macros

docs/src/config.md, src/Revise.jl
Fixes #184. The code changes are designed to be backwards-compatible. However, I'd like to understand how to work around behavioral changes this will cause for IJulia.
=> Change recommendations on startup.jl

src/parsing.jl, test/REQUIRE, test/runtests.jl
Hmm, this is a branch that I seem to have been running on for a while and forgotten to merge to master. Oops.
=> Ensure parse_module! doesn't trigger eval unnecessarily

src/parsing.jl, test/runtests.jl
This generates more compact & readable output by Rebugger, by leaving in-body macros intact.
=> Avoid expanding macros in function bodies with a docstring

.travis.yml, README.md, docs/Project.toml, docs/make.jl, docs/src/dev_reference.md, src/exprutils.jl
This also fixes some accumulated problems with the doctests.
Ref #204
=> Switch to the new Documenter

.travis.yml, REQUIRE, appveyor.yml, src/Revise.jl, src/parsing.jl, src/pkgs.jl, src/recipes.jl, test/runtests.jl
This was triggered by running some of the Rebugger demos
=> Find code for Pkg

docs/src/index.md
CC @rulatir, does this seem to be more what you had in mind?
=> Expand the usage example in docs (fixes #225)

src/lowered.jl
Fixes https://github.com/timholy/CodeTracking.jl/issues/27
CC @pfitzseb
=> Disable breakpoints before executing code

src/lowered.jl
This needs a test but it would be more complicated than I have time to figure out now.
=> Check that frame is a leaf-frame (fixes #268)

Project.toml, REQUIRE
This fixes serious problems caused by #265. See also https://github.com/JuliaLang/METADATA.jl/pull/22680.
=> Increase the minimum version on LoweredCodeUtils

src/Revise.jl, test/runtests.jl
=> includet handles path via task_local_storage

.travis.yml, src/relocatable_exprs.jl, test/runtests.jl
=>  Insist on type-equality when comparing numbers in expressions

src/Revise.jl, test/runtests.jl
=> Throw error when trying to track single files from Base or stdlibs

src/logging.jl, src/lowered.jl, test/runtests.jl
=> Show revision errors to the user (fix #281)

Project.toml
This PR + a new release should fix #293
=> Relax requirement on LoweredCodeUtils

src/lowered.jl
Will be needed for https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/259.
=> fix Revise breakpoint toggling with new breakpoint implementation in JuliaInterpreter

.travis.yml, src/Revise.jl, test/inotify.jl
=> Fix inotify warning

Project.toml
for compatibility with JuliaInterpreter 0.6.
=> update to 2.1.6

docs/src/index.md
Suggested on [Discourse](https://discourse.julialang.org/t/more-basic-revise-usage-with-module/27517/8).
=> Mention autoloading at beginning of docs

.travis.yml, appveyor.yml, src/pkgs.jl, src/utils.jl, test/common.jl, test/runtests.jl
Needs https://github.com/JuliaLang/julia/pull/32961, but let's see if there are any other failures.
=> Update tests for Julia 1.3

src/pkgs.jl, test/runtests.jl
=> Don't update directory mtime for irrelevant changes

src/Revise.jl, test/runtests.jl
Some of this is just a cleanup of various branches I had lying around. It also aims to diagnose travis timeouts, and most importantly fixes #350.
=> Various fixes (fixes #350)

src/pkgs.jl
=> check staleness before trying to verify the header

src/Revise.jl
=> Make Revise.juliadir more robust

docs/src/index.md, docs/src/internals.md, src/Revise.jl, src/lowered.jl, src/pkgs.jl, src/utils.jl, test/runtests.jl, test/sigtest.jl
Fixes #107. Also makes small improvements to the documentation (mainly in acknowledging the broader mission of Revise).
=> Improve error-reporting and handle new `include`d files

Project.toml, src/lowered.jl
Fixes #363. @cstjean, can you test? Requires https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/20 (which is where all the real work is done).
=> Switch to O(N) LoweredCodeUtils

.gitignore, src/logging.jl, src/lowered.jl, src/utils.jl, test/callee_error.jl, test/runtests.jl
EDIT: this now makes the error reporting much more consistent among different branches.
=> Show the message when reporting evaluation errors

.travis.yml, appveyor.yml, src/Revise.jl, src/lowered.jl, test/runtests.jl
Fixes #147 and https://discourse.julialang.org/t/how-do-i-make-revise-jl-work-in-multiple-workers-environment/31474
=> Ensure anonymous functions synced on workers

src/Revise.jl, src/pkgs.jl, src/precompile.jl
Fixes #403 
This PR also improves the precompile statements.
=> Wait for module initialization when tracking files

NEWS.md, Project.toml, src/pkgs.jl, test/runtests.jl
Fixes #244. In contrast with #232, there are no manual interventions needed. CC @Djoop, @oschulz, @rafaqz
To work this requires a PR to Requires, https://github.com/MikeInnes/Requires.jl/pull/69.
=> Support new files added by Requires

NEWS.md, docs/src/user_reference.md, src/Revise.jl, test/runtests.jl
Attempt at https://github.com/timholy/Revise.jl/issues/407
=> Reprint error

docs/src/cookbook.md
Inspired by 
https://discourse.julialang.org/t/change-in-local-package-does-not-take-effect-unless-julia-restart/32612
=> Docs: emphasize `dev` rather than `add`

src/parsing.jl, test/runtests.jl
=> Improve line-number detection in parse errors

src/Revise.jl, src/lowered.jl, test/runtests.jl
Fixes #418. Can you test @tpapp?
=> Retry revisions on InterruptException

src/pkgs.jl
=> Allow more than one non-stale file

src/lowered.jl, test/backedges.jl, test/common.jl, test/runtests.jl
=> Handle function declaration followed by thunk

src/Revise.jl
This allows us to use the root task as the REPL backend.
Fixes https://github.com/JuliaLang/julia/issues/35185
=> intercept REPL without replacing the backend Task

src/types.jl
Due to https://github.com/JuliaLang/julia/pull/34660
=> Fix tests on nightly

docs/src/config.md
Motivated by https://github.com/JunoLab/Juno.jl/issues/532. CC @VoSiLK and @pfitzseb.
=> Distinguish NFS from NTFS in docs

.travis.yml, docs/src/dev_reference.md, docs/src/index.md, src/Revise.jl, src/backedges.jl, src/utils.jl, test/populate_compiled.jl, test/runtests.jl
This is designed to catch issues like what happened in #460, but also more generally improve test coverage.
=> Improve test coverage

src/backedges.jl, src/lowered.jl, test/backedges.jl
This connects uses of a variable to its definition. ~~This doesn't fix any known bugs but it will be useful for a slightly modified version of #473,~~ It fixes Revise on nightly and is another step towards #249.
=> Backedges: include names in chunk calculations

src/lowered.jl
The two sources fixed here are lack of type information for `lnn` and julia#15276.
=> More invalidation reduction

Project.toml, src/Revise.jl, src/lowered.jl, src/pkgs.jl, test/runtests.jl
=> Preserve evaluation module for includes in eval_new!

Project.toml, src/Revise.jl, src/backedges.jl, src/types.jl, test/common.jl, test/runtests.jl
Together with https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/412 and https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/37, this fixes #509. CC @quinnj.
=> Support GotoIfNot and ReturnNode

src/pkgs.jl
xref https://github.com/JuliaLang/julia/pull/37624
=> Exploit `explicit_manifest_entry_path` for package file locations

test/runtests.jl
The fix was https://github.com/JuliaLang/julia/pull/37626
Closes #197
Closes #198
=> Check that module docstrings are properly updated (closes #197)

docs/src/config.md, docs/src/index.md
=> Document Revise's latency costs

src/packagedef.jl
=> Exempt `exit()` from revision-processing

src/lowered.jl, src/packagedef.jl
xref https://github.com/timholy/CodeTracking.jl/pull/73
=> Improve inference in a couple of spots

docs/src/config.md
=> Config: don't assume error has msg field

src/packagedef.jl, test/runtests.jl
=> Don't error for REPL-entered comments

Project.toml, test/runtests.jl
We should test here that #568 stays fixed. The fix in https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/54 is very focused, which is good, but we want to make sure the overall behavior works.
CC @cstjean
=> Add test for issue 568

src/lowered.jl, test/runtests.jl
Workaround for julia#38819
Fixes #583
=> Fix adding docstring to module with none

Project.toml, test/runtests.jl, test/sigtest.jl
With https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/447 we no longer need to jump through hoops.
=> Clean up the signature tests and Pkg namespacing

src/precompile.jl
These were discovered with snoopi_deep.
=> Add some precompiles

Project.toml, test/runtests.jl
The test requires LoweredCodeUtils 1.2.8, but there is no change in
Revise itself.
=> Add test for issue #599

Project.toml, src/precompile.jl, test/runtests.jl
Add test for #606
Closes #606.
The bug happens only for Julia versions prior to 1.6.
=> Version 3.1.13

src/precompile.jl
=> Turn precompile asserts into warnings

Project.toml, src/lowered.jl
xref: https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/62
=> update to LoweredCodeUtils@2.0.0

src/precompile.jl
since JuliaLang/julia#39593, this statement was not working anymore
=> fix precompile warning on Julia nightly

src/packagedef.jl, test/runtests.jl
=> Prevent double-execution

docs/src/limitations.md
Didn' t find this in official doc. Might include this for better visibility of this workaround.
=> add current type mutation workaround doc

Project.toml, src/recipes.jl
Fix https://github.com/timholy/Revise.jl/issues/659.
=> Add stdlib NetworkOptions to recipes

.github/workflows/ci.yml, src/packagedef.jl, test/common.jl, test/runtests.jl, test/start_late.jl
=> Fix REPL for manually-loaded Revise

test/runtests.jl
This is a non functional change (NFC), rewriting `runtests.jl` by replacing:
```julia
open(path, "w") do io
print(io, ...)
end
```
with:
```julia
write(path, ...)
```
Also make indentation consistent (one indentation level) on these `write`s.
I know `NFC`s are controversial, but IMO in this case, removing `400+` lines in a `~4000` lines file is worth considering for readability.
=> NFC simplify `runtests.jl` (rework `write`s)

src/types.jl, test/runtests.jl
Corrects some typos in the repository.
=> Fix some typos

.github/workflows/ci.yml
Suggestion from https://github.com/timholy/Revise.jl/pull/769#issuecomment-1886030780
=> Add continue-on-error to CI

docs/src/config.md
At once updated link to Linux resource.
=> Update band-aid info on file watching (#778)

docs/src/config.md, docs/src/index.md
=> Add docs on editor configuration

docs/make.jl, docs/src/index.md, docs/src/tricks.md, src/packagedef.jl
=> Add docs on trick for handling REPL

src/precompile.jl
=> Fix precompile statement

test/runtests.jl
Test that the fix in Julia 1.12 persists and that Revise handles it
properly.
CC @LilithHafner
=> Add a test for #883

Project.toml, src/lowered.jl
Fixes #903
This is split out from #894.
=> Avoid redefining types in sigs mode

Project.toml, src/Revise.jl, src/lowered.jl
Use `lookup(frame, node)` instead of `@lookup(frame, node)`
=> update to JuliaInterpreter 0.9.46

src/lowered.jl, src/packagedef.jl, src/precompile.jl, test/runtests.jl
Separate functions based on what they return.
=> some minor refactoring on `methods_by_execution!`

src/loading.jl, src/packagedef.jl, src/pkgs.jl, src/utils.jl
Separated from the refactoring I'm working on locally.
=> some more minor cleanups on the code base

src/packagedef.jl, src/pkgs.jl, src/recipes.jl
=> Add additional locking for thread safety
