- test/runtests.jl
I'm assuming the tests in the catch blocks are intended to always run?
> ensure that the try-catch blocks don't silently pass

- src/Revise.jl
Vim seems to trigger "renamed" rather than "changed", so it's probably better not to worry about the return value. If the file can't be found another error will catch it anyway.
> Don't be so picky about results of file-watching (fixes #6)

- src/Revise.jl
Importing SymEngine (which is a dependency of DifferentialEquations) with Revise currently fails:
```julia
julia> using Revise; using SymEngine
ERROR: deps_file not recognized
Stacktrace:
[1] parse_expr!(::Dict{Module,Set{Revise.RelocatableExpr}}, ::Expr, ::Symbol, ::Module, ::String) at C:\Users\heichhorn\.julia\v0.6\Revise\src\Revise.jl:384
[2] parse_source!(::Dict{Module,Set{Revise.RelocatableExpr}}, ::Expr, ::Symbol, ::Module, ::String) at C:\Users\heichhorn\.julia\v0.6\Revise\src\Revise.jl:348
[3] parse_expr!(::Dict{Module,Set{Revise.RelocatableExpr}}, ::Expr, ::Symbol, ::Module, ::String) at C:\Users\heichhorn\.julia\v0.6\Revise\src\Revise.jl:365
[4] parse_source!(::Dict{Module,Set{Revise.RelocatableExpr}}, ::String, ::Symbol, ::Int64, ::Module, ::String) at …
```
> Handle cases were include paths are saved to a var

- src/Revise.jl
- test/REQUIRE
- test/runtests.jl
This is an attempt at a more robust solution to #15 than was #16. It has some disadvantages---for example, editors that autosave a tempfile to a watched directory will trigger a callback to Julia---but given that OSX struggles with watching a lot of files, this may be the best solution.
CC @cstjean, @sampowell. I've tested this a bit and it seems OK to me, but it might be nice to hear reports from OSX users. Note that this is back to watching GSL, so you should get an error pretty quickly if this is not working.
> Watch directories rather than files

- REQUIRE
- src/Revise.jl
- test/runtests.jl
We could then add a user-facing function that forces reloading every rex in a module. This would be a work-around for the macro/generated function issues.
On both master and this branch, I'm getting a failure, four times out of five:
```julia
Cleanup: Test Failed
Expression: contains(readstring(warnfile), "is not an existing directory")
Stacktrace:
[1] macro expansion at /Users/cedric/.julia/v0.6/Revise/test/runtests.jl:457 [inlined]
[2] macro expansion at ./test.jl:860 [inlined]
[3] macro expansion at /Users/cedric/.julia/v0.6/Revise/test/runtests.jl:445 [inlined]
[4] macro expansion at ./test.jl:860 [inlined]
```
I haven't investigated, but I printed `warnfile`, and it's empty.
> Use OrderedSet

- src/Revise.jl
Avoids a warning with `Revise.track(Base)`
> Support `Core.include(module, filename)`

- src/Revise.jl
- test/runtests.jl
This is the easiest definition to support #41. I wish that `parse_pkg_files` returned the files in evaluation order, but I can't quite follow its logic to fix it. In any case, I don't think the order matters for #41: if I modify a macro's definition in MyModule.jl and call `revise(MyModule)`, the macro will be updated by the regular `revise()` call before `revise(MyModule)` is executed.
Alternatively, we could define `module2files` as an inverse of `file2modules`, but it's not as straight-forward, and I didn't see any upside.
> Add module2files

- README.md
- src/Revise.jl
- test/runtests.jl
As suggested in https://github.com/timholy/Revise.jl/pull/33#issue-247406423
Issues:
- I like `revise(module)` as a verb, but it's not entirely obvious what it's going to do.  `forcerevise(module)`? 
- Both here and in TraceCalls.jl, I get the module files from `parse_pkg_files`, which seems a tad wasteful given that those files were already parsed. We could maintain `module2files`.
- `revise(module)` triggers a lot of redefinition warnings. In ClobberingReload I use [this code](https://github.com/cstjean/ClobberingReload.jl/blob/master/src/scrub_stderr.jl). We could move over `scrub_stderr` to Revise.jl
This is a work-around for #20 and #31, I'll leave you to decide if you want to close these issues.
> revise(module) to force reevaluating every expression

- src/Revise.jl
- test/REQUIRE
- test/runtests.jl
https://github.com/JuliaLang/julia/pull/23579 changed how modules are loaded, and for Revise's purposes the important change appears to be that the module isn't externally available while its `__init__` method is being run or when `Base.package_callbacks` are being run. This `@schedule`s Revise's workflow until after module definition is completely finished. @JeffBezanson, is this correct (and intended)? The first commit is the one that implements the fix.
Also fixes some deprecations, and attempts to fix test failures on OSX (I'm just guessing here). CC @cstjean
> Fix Revise on 0.7

- src/Revise.jl
One of the biggest negatives of Revise is that it slows package loading. It turns out that the majority of the bottleneck comes from having the callbacks be made with `invokelatest`: if you change [this line](https://github.com/JuliaLang/julia/blob/6dfaea5c22b24b07254903d1c2c71742d4a04843/base/loading.jl#L333) to `callback(mod)` it dramatically cuts the load time. Unfortunately, with that change, I find that I can't `push!` a callback to `Base.package_callbacks` from within the module's `__init__` method due to world age problems.
Fortunately, the simple trick in this PR basically fixes the problem.
Demo, starting with `julia --startup-file=no` so I avoid loading Revise by default (using Julia 0.6, it's *much* worse on 0.7, 4s vs 13s):
```julia
julia> using Revise
julia> using Example  # …
```
> Fix `invokelatest` bottleneck by using scheduling

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- src/Revise.jl
- src/parsing.jl
- src/relocatable_exprs.jl
- src/types.jl
- test/REQUIRE
- test/runtests.jl
This is based on ~~the not-yet-merged~~ https://github.com/JuliaLang/julia/pull/23898. Locally it passes all tests ~~until it gets to the `Revise.track` tests, because there I haven't expunged the dependence on parsing. I'm posting this now because there seems to be room to discuss how this should work:~~
- ~~`Revise.track(Base)`: perhaps the best approach here would be for `base/sysimg.jl` to keep track of the files it includes, and Revise could just look that information up.~~
- ~~More interesting is `Revise.track(filename)`, which I'm thinking of in the context of "scripts" for test or analysis code. Currently we recursively track any file `included` by that file, based on parsing. If we wanted to replicate that, note that the new `Revise.included_files` list includes the entire set, …
> Eliminate need to parse include paths

- README.md
- src/Revise.jl
- test/runtests.jl
This is an alternative to #84. This version is both simpler and supports method deletion.
> Support distributed revision (fixes #82)

- src/Revise.jl
Newer Juno versions use a standard REPL, so `elseif` isn't appropriate here.
> Fix Juno integration

- .travis.yml
I had disabled the custom travis script because it appeared to be causing trouble, but then noticed that without it the "polling" tests don't run. This is an attempt to re-enable it.
> Re-enable custom test code on travis

- src/Revise.jl
This seems to be a new depwarn.
Also show the error message from parsing/eval errors.
> Fix depwarn about missing catch

- src/delete_method.jl
- test/runtests.jl
Julia 0.7 supports functions like
```julia
function foo(x, (count, name))
body
end
```
This PR changes the parsing of signatures to handle these correctly.
> Support method deletion for destructured arguments

- .travis.yml
- docs/src/index.md
- src/Revise.jl
- test/runtests.jl
We were not supporting the full range of startup options. Most seriously, one combination ended up blocking the REPL (fixed by putting in an `@async` block).
> Fix a couple of bugs related to REPL-stealing

- src/Revise.jl
Elimitates the warning message after https://github.com/JuliaLang/julia/pull/26991
> Remove __precompile__, as it is now the default.

- REQUIRE
- docs/src/dev_reference.md
- docs/src/internals.md
- src/Revise.jl
- src/delete_method.jl
- src/parsing.jl
- src/pkgs.jl
- src/recipes.jl
- src/relocatable_exprs.jl
- src/types.jl
- test/common.jl
- test/runtests.jl
This is a major redesign of Revise's internals. It is now organized around two "maps" (Dicts), one which connects expressions to Julia types and the other which goes in the opposite direction. Together the two can be leveraged for an accurate and efficient connection between methods and the source-expressions that define them.
One nice consequence of this change is that we can finally fix #51. It depends on some cooperation from Base, however: https://github.com/JuliaLang/julia/pull/28328.
> Redesign Revise for bidirectional `expr`<-->`method` capabilities

- docs/src/user_reference.md
- src/Revise.jl
- src/exprutils.jl
- src/recipes.jl
- src/relocatable_exprs.jl
- test/runtests.jl
Plus another pile of fixes. The new signature parsing places many more demands on accuracy, it seems, so the v0.6 rewrite has led to several problems. However, in several respects it's already better than ever, so I am pretty confident this is moving in the right direction.
> Add includet to simplify script-tracking

- src/Revise.jl
- src/types.jl
Motivated by the slowness of `track(LinearAlgebra)`, I profiled and found a surprising result: almost all the time was spent on type-inference for inserting `sigtmap[sigt] = def`. Given that each key has a different type, perhaps this shouldn't have been surprising. By switching to an IdDict it got faster.
Before:
```julia
julia> using LinearAlgebra
julia> @time Revise.track(LinearAlgebra)
89.868081 seconds (233.75 M allocations: 11.436 GiB, 3.34% gc time)
```
After:
```julia
julia> @time Revise.track(LinearAlgebra)
3.469887 seconds (5.75 M allocations: 214.248 MiB, 4.76% gc time)
```
CC @andreasnoack
> Greatly improve performance with IdDict

- .travis.yml
- src/Revise.jl
This makes no sense, but it reproducibly fixes the test failures. Thanks to @andreasnoack and @vtjnash.
Andreas also mentioned that on OSX there are times where methods don't update until you insert a `print` statement (which yields) into the method body. This suggests that we may need to insert more `yield`s in more places. But it makes sense to go stepwise, so let's start here.
> Fix test failures on OSX

- src/Revise.jl
- src/exprutils.jl
- test/runtests.jl
I was unnecessarily conservative in my previous implementation of this syntax; the fix is simply to drop what I thought was a "sanity check."
> Parse return-type declarations with wheres clauses

- docs/src/dev_reference.md
- src/Revise.jl
- src/recipes.jl
- test/runtests.jl
This is designed to support Revise.track(Base) on a wider array of machines. This is becoming important because of [Rebugger](https://github.com/timholy/Rebugger.jl). This may fix https://github.com/timholy/Rebugger.jl/issues/1 ~and the longstanding Travis failures on OSX.~ (EDIT: those were fixed in #136)
> More robustly find `base` (and the stdlibs)

- src/Revise.jl
- src/pkgs.jl
- src/recipes.jl
- test/runtests.jl
Now we update the paths to Base and stdlib files on the user's system. Unfortunately, the `basesrccache` is "indexed" by the paths as they were at build time. Consequently we need to hold on to both.
> Use original path for indexing basesrccache

- .travis.yml
- appveyor.yml
- docs/make.jl
- docs/src/config.md
- docs/src/index.md
- src/Revise.jl
As Revise gets more ambitious about tracking more and more of Julia, it seems likely that path-related problems will be the number one source of trouble for users. Rather than just respond to issues as they come up, let's have some documentation that walks through the process of diagnosing and fixing path problems.
> Document the steps needed to fix path problems

- REQUIRE
- src/Revise.jl
- src/pkgs.jl
- test/runtests.jl
Base's version recently discarded the submodule names, so it's time to maintain our own version here.
Fixes #142. CC @pawbz.
> Use our own version of parse_cache_header

- src/exprutils.jl
- src/parsing.jl
- test/REQUIRE
- test/runtests.jl
Boy, this was really dumb. I was implicitly assuming that macros don't modify the method signature. :disappointed_relieved: 
Fixes #148 . CC @mkborregaard, @daschw.
> Parse properly when macros redefine methods

- docs/make.jl
- docs/src/config.md
- docs/src/debugging.md
- docs/src/dev_reference.md
- docs/src/index.md
- src/Revise.jl
- src/types.jl
- test/revisetest.jl
- test/runtests.jl
This may help catch weird/rare errors. CC @pfitzseb, @vtjnash.
> Add a logging framework

- docs/src/debugging.md
- docs/src/user_reference.md
- src/Revise.jl
- src/parsing.jl
- src/recipes.jl
- src/relocatable_exprs.jl
- test/runtests.jl
This may fix #161. The log suggests that most or all of the revised expressions used gensymmed symbols. This PR should make them compare (and hash) as equal.
This also adds a little more debug info.
> Don't do spurious revisions

- docs/src/debugging.md
- docs/src/user_reference.md
- src/Revise.jl
- src/logging.jl
- src/parsing.jl
- src/recipes.jl
- src/types.jl
- test/runtests.jl
It turns out that using TestLogger interacted with `@testset`. Consequently, it's better to use something completely independent. The overall design of the logger mimics that of TestLogger.
This also adds some convenience utilities and nicer printing. Overall it makes it considerably nicer to collect and inspect logs.
> Create our own custom logger

- src/relocatable_exprs.jl
- test/revisetest.jl
- test/revisetest_errors.jl
- test/revisetest_revised.jl
- test/runtests.jl
I am guessing this *should* fix #161 (CC @pfitzseb). In any event I can verify that it is an improvement even on my own machine, so even if this doesn't fix #161 I am confident we want this.
> Prevent spurious re-evaluation of more docstrings

- src/exprutils.jl
- src/parsing.jl
- src/relocatable_exprs.jl
- test/runtests.jl
I'm not quite sure if and when this changed (it clearly wasn't being tested), but a prime suspect is the switch to computing signature types. At any rate, this fixes the problem and adds good tests so this won't regress.
CC @quinnj.
> Detect changes in performance annotations (fixes #165)

- src/Revise.jl
- src/exprutils.jl
- src/recipes.jl
This should fix #168 by ~~basically having Revise ignore changes to Base files unless the user has a source-build of Julia. Since we'd like to have them commit their improvements back to Base anyway, this is just incentive for good behavior :smile:.~~
allowing the caller to choose whether to process the files that trigger the `mtime` criterion.
@pfitzseb, does this fix #168 for you?
> Optionally return the list of modified files from Revise.track(Base)

- src/Revise.jl
- src/exprutils.jl
- test/runtests.jl
This works around https://github.com/JuliaLang/julia/issues/28899 and probably fixes #137
New tests:
- test https://github.com/JuliaLang/julia/issues/28899
- test for signature-changes with a gensymmed type
- test that changes that do not fundamentally change the type signature do not result in inadvertent deletion (probably #137).
> Swap the order of deletion and evaluation

- src/Revise.jl
- src/pkgs.jl
- src/precompile.jl
This also reorganizes some functions to make them more precompile-friendly.
On my machine this drops the time for `@time (using Revise; revise())` from 3.1 seconds to 1.5 seconds. I'd like to get it even lower, but this is a worthy step forward.
> Add a few precompiles for faster startup

- src/exprutils.jl
- test/REQUIRE
- test/runtests.jl
The important change here is [a single line](https://github.com/timholy/Revise.jl/compare/teh/fix_183?expand=1#diff-e017b612ac9926c6c378bf32adf520b3R101), but I took the occasion to throw in a few more improvements. In particular, EponymTuples is now a test-dependency of Revise, which may make it easier to ensure we continue to support it.
I was not able to replicate the exact error in #183, can you test @tpapp?
>  Fix module scoping in call to sig_type_exprs (fixes #183) 

- src/exprutils.jl
- test/runtests.jl
> Fix sigex when module has a submodule named `Core` (fixes #199)

- src/Revise.jl
- src/exprutils.jl
- test/runtests.jl
This allows `get_def` to succeed with many more methods (with respect to Base, about 700 more methods). In particular, it finally supports methods with signatures like `f(a::AbstractVector{<:Integer})`, which has formerly been a real limitation for Rebugger.
The downside is it may slow Revise down a bit (for the cost of running type-intersection), but in playing with this locally I haven't noticed any real problems.
> Use type intersection to match signatures to those of methods

- docs/src/dev_reference.md
- docs/src/index.md
- src/Revise.jl
- src/pkgs.jl
- src/precompile.jl
- src/recipes.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
Switching between `free` and `dev` has become my main reason to restart Revise, so it's finally time to fix #146.
This is a breaking change. When tagged this will become Revise version 1.0.0.
> Follow switches between `free` and `dev`

- src/Revise.jl
- src/pkgs.jl
- src/recipes.jl
- src/utils.jl
The new internal framework breaks Rebugger, but this makes it easier to update it.
> Small reorganization to simplify porting Rebugger

- docs/src/dev_reference.md
- src/Revise.jl
- src/exprutils.jl
- src/pkgs.jl
- src/precompile.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
In my testing this shaves about 35% off the startup time of Revise. Not awesome, but not too bad either. If we could get those 4 commented-out `setindex!` methods to precompile, it would shave an additional 15% off from where this is now.
> Improve startup latency

- src/recipes.jl
This is hard to test since it's only triggered by editing files in Base twice.
> Fix double-revisions of Base files

- src/exprutils.jl
- src/parsing.jl
- test/runtests.jl
It would be nice if Revise.jl notices `Base.@​propagate_inbounds` etc. are the "annotation" macro.  Is this the right approach?
> Allow Base.@​propagate_inbounds etc.

- src/Revise.jl
- src/pkgs.jl
Lately, I've been seeing accidental exit from Julia REPL with error like this:
```julia
ERROR: MethodError: Cannot `convert` an object of type Array{Union{Ptr{Nothing}, Base.InterpreterIP},1} to an object of type Bool
Closest candidates are:
convert(::Type{T<:Number}, ::T<:Number) where T<:Number at number.jl:6
convert(::Type{T<:Number}, ::Number) where T<:Number at number.jl:7
convert(::Type{T<:Integer}, ::Ptr) where T<:Integer at pointer.jl:23
...
Stacktrace:
[1] setproperty!(::REPL.LineEditREPL, ::Symbol, ::Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}) at ./Base.jl:19
[2] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:139
[3] (::getfield(REPL, Symbol("#do_respond#38")){Bool,getfield(REPL, …
```
> Support catch_stack API

- README.md
Currently the logo is so big it dominates the page, I've made it smaller and centered it in the readme.
Feel free to close if you prefer to current style!
> Smaller logo and center it

- .travis.yml
- REQUIRE
- appveyor.yml
- src/Revise.jl
- src/exprutils.jl
- src/pkgs.jl
- src/recipes.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
This sets up [CodeTracking.jl](https://github.com/timholy/CodeTracking.jl) as the new "query interface" of Revise.
> Integrate with CodeTracking

- src/Revise.jl
- test/common.jl
- test/runtests.jl
This had broken and our tests were inadequate to catch that. (Also obscured by the fact that this gets called from Base inside a `try/catch`.) This also generalizes the correction so that it can either take a `(frame, nrepetitions)` or just a `frame`.
> Fix line number correction in stack traces

- src/pkgs.jl
- test/runtests.jl
I was checking, but it was too late. Just moved it up a little earlier.
> Check for `nothing` return from `parse_source` (fixes #257)

- Manifest.toml
- Project.toml
- REQUIRE
- src/Revise.jl
- src/lowered.jl
- src/pkgs.jl
- test/runtests.jl
This fixes #263 and also updates to JuliaInterpreter 0.4. Also addresses the TODO item in #258 and fixes a missed aspect of #254.
CC @essenciary
> Prevent double-evaluation in `includet`

- docs/src/limitations.md
- test/runtests.jl
Revise 2.0 ended one of Revise's main limitations, but I had not yet eliminated it from the docs.
> Test deletion of atsign-evaled method and update docs

- src/Revise.jl
- test/runtests.jl
Relies on https://github.com/JuliaLang/julia/pull/31514
> Implement line number correction for methods and method lists

- Project.toml
- REQUIRE
- docs/src/index.md
- docs/src/user_reference.md
- src/Revise.jl
- test/runtests.jl
This is an oft-requested feature whose solution was pioneered in discussion in #203. I initially felt it was orthogonal to Revise, but one important thing changed: Revise's ability to follow `dev->add` and back means that a low-level implementation in terms of absolute paths would be painful from the user side. So, at the risk of growing this package, it now seems to belong here.
I also have the sense that usage of `includet` is getting out of hand. I suspect some of its users are really after `entr`.
CC @mlhetland, @essenciary, @yurivish
>  Add `entr` to do work when files update 

- appveyor.yml
`julia_version: 1` actually calls the latest stable version, i.e., `julia v1.1.0`
> fix appveyor julia version

- src/lowered.jl
- test/runtests.jl
Might be part of https://discourse.julialang.org/t/segmentation-fault-when-updating-packages/23766?
> In eval-ed expressions, don't try to extract methods from toplevel-evaling expressions

- src/Revise.jl
Unless there is something I am missing, `watch_file` throws a `Base.IOError`, not `SystemError`:
```
julia> using FileWatching; try watch_file("test.jl") catch e e end
Base.IOError("FileMonitor (start): no space left on device (ENOSPC)", -28)
```
So currently the warning about used up inotify capacity actually never gets shown and Revise just silently refuses to update definitions.
> Use correct error type for inotify warning

- src/lowered.jl
- test/common.jl
- test/runtests.jl
The simplified example due to @simonbyrne in #309 generates a frame that looks like this:
```julia
frame = Frame for ParamTest
1  5  1 ─      const c
2  5  │        c = 1.2
3  5  │   %3 = (Base.Docs.Binding)(ParamTest, :c)
4  5  │   %4 = (Core.svec)("    mydoc\n")
5  5  │   %5 = (Dict)(:path => "/home/tim/.julia/packages/ParamTest/CpquX/src/ParamTest.jl", :linenumber => 5, :module => ParamTest)
6  5  │   %6 = (Base.Docs.docstr)(%4, %5)
7  5  │   %7 = (Core.apply_type)(Union)
8  5  │   %8 = (Base.Docs.doc!)(ParamTest, %3, %6, %7)
9* 5  └──      return %8
```
The fundamental error here is that `%8` was not formerly being assigned. I've also set this up so that, should we eventually get the ability to handle #20, macro-defined docstrings should update if modified.
> Assign docstring created by a macro (fixes #309)

- src/Revise.jl
This PR has three minor modifications to `entr` (cf. #298):
- By default, `entr` will now execute `f()` initially, unless the `postpone` keyword is used;
- `entr` sleeps for the amount given by `pause` between being triggered and executing `f()`, to handle clusters of modifications, such as text editor saves; and
- Rewrites *to* a given file/file name are now accepted as modifications; rewrites *from* the file name cause an error, as the file with the supplied name no longer exists.
The first and last are in line with the `entr` command line tool. The second is an added convenience, to avoid redundant execution when (e.g.) generating output based on saved files, etc.
The modifications are independent – no need to accept them all.
(Note: No new tests have been added for these features.)
> Rewrite, postpone and pause

- Project.toml
Tested locally with JuliaInterpreter 0.7 and passes. For this to run on CI, the PR to General for 0.7 needs to be merged and LoweredCodeUtils also needs new compat + tag.
> add compatibility with JuliaInterpreter 0.7

- Project.toml
- src/Revise.jl
- src/lowered.jl
- test/runtests.jl
Fixes https://github.com/timholy/CodeTracking.jl/pull/48
> Use `bodymethod` if location info is missing

- .travis.yml
- docs/make.jl
- docs/src/cookbook.md
- docs/src/index.md
- docs/src/limitations.md
In response to https://discourse.julialang.org/t/trying-and-trying-with-revise/27915
> A usage cookbook

- src/pkgs.jl
Ensure that we parse into the correct module. This seems to fix #312. Testing this is brutally hard, so let's just take the fix and call it a day.
> Improve module hygiene when parsing code (fixes #312)

- Project.toml
- src/Revise.jl
- test/runtests.jl
Fixes #302, although it also needs ~~a little something on the JuliaIntepreter side.~~ https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/331 ~~works, but it's a little weird, so I'm going to leave this here until I have a chance to dig a little more.~~
> Don't interpret `includet` (workaround for #302)

- src/Revise.jl
- src/lowered.jl
- src/parsing.jl
- src/relocatable_exprs.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
This should generate error messages much more similar to Base's. The biggest change here is to avoid calling `unwrap` on the stored expressions, which produced better location info in some cases but necessitated some changes elsewhere.
Also, @mlhetland and @essenciary, I have disabled the `entr` tests on OSX. They have been the cause of [many failures](https://travis-ci.org/timholy/Revise.jl/builds) (note I went through a period where I allowed failures on OSX, so some of those green checks are a bit misleading). I have tried several approaches (e.g., 77cfdcb3f1c71eeec2bacebcbfdb43a3cb5dba38, e22ec82548c103f97cccb6a5d7b024e65fda759c, f1645112a28833dd9ad20376a794dc367ae33160, 8c60017f70824a264e37367fecf1cf89eb80c578) without completely nailing the problem. Because `entr` is a bit …
>  Improve error message in case of parsing problems (fixes #301) 

- src/Revise.jl
- test/runtests.jl
Incorporates @timholy's fix and adds my test.
Note: The test does not properly exercize the added `yield()` statement.
> Test and fix for issue #354

- src/parsing.jl
- src/types.jl
- test/runtests.jl
Fixes the important part of #358. The first commit is the important one, the second commit is largely cosmetic (to make the tests pass even if the user is running with `JULIA_REVISE_INCLUDE=1`).
> Don't use "." as the basedir

- src/recipes.jl
- test/runtests.jl
Does not work well enough for prime-time, but still might have useful functionality for people working on the compiler.
Current status:
```julia
julia> using Revise
[ Info: Recompiling stale cache file /home/tim/.julia/compiled/v1.1/Revise/M1Qoh.ji for Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
julia> Revise.track(Core.Compiler)
file = "base/compiler/abstractinterpretation.jl"
file = "base/compiler/bootstrap.jl"
file = "base/compiler/inferenceresult.jl"
file = "base/compiler/inferencestate.jl"
file = "base/compiler/optimize.jl"
file = "base/compiler/params.jl"
file = "base/compiler/ssair/domtree.jl"
file = "base/compiler/ssair/driver.jl"
file = "base/compiler/ssair/inlining.jl"
file = "base/compiler/ssair/ir.jl"
file = "base/compiler/ssair/legacy.jl"
file = …
```
> Re-activate Core.Compiler (fixes #270)

- src/Revise.jl
- test/runtests.jl
This issues a continuous reminder about files that are out-of-sync. Fixes #317, fixes #321.
I may not merge this immediately, this seems like the kind of change that would be good to try out before making it the standard. @oschulz and @ianshmean, can you try out this branch and see how you like it?
> Preserve revision_queue items that errored

- src/types.jl
This fixes a test failure on nightly, ref https://github.com/JuliaLang/julia/pull/33290.
> Define `Base.typeinfo_prefix` for ModExSigs

- src/Revise.jl
update to https://github.com/JunoLab/Atom.jl/pull/177
Actually the `evalrepl` handler hasn't been used in recent Juno versions, thus I think we even don't need version compat checks for this change.
> update to https://github.com/JunoLab/Atom.jl/pull/177

- src/pkgs.jl
- test/runtests.jl
Fixes #371. See also #383. Might fix #381
> Add fallback for stale cachefiles

- NEWS.md
- docs/src/limitations.md
- src/Revise.jl
- src/pkgs.jl
- src/recipes.jl
- src/utils.jl
- test/runtests.jl
This is essentially the opposite operation from #386.
This proved much more interesting than expected: it revealed a bug in which `Pkg/src/REPLcompletions.jl` was confused for the REPL stdlib. Consequently this PR also fixes that bug.
> Handle file deletion and fix stdlib paths

- src/Revise.jl
- src/parsing.jl
- test/runtests.jl
Previously it reported a line number of 0, and in practice this made it quite hard to determine the cause of the error.
> Report the line number for parsing errors

- src/backedges.jl
- test/backedges.jl
I am not quite why the offending check was there (it doesn't seem to make a lot of sense), but it doesn't seem to break anything to remove it. I am guessing it's a legacy of the order in which stuff was developed.
> Record correct assignment line (fixes #399)

- Project.toml
- src/pkgs.jl
- test/runtests.jl
For a simple call expression inside the `@require`, this was adding a new argument.
> Fix the handling of atsign-requires

- docs/Project.toml
- docs/src/config.md
- docs/src/cookbook.md
- docs/src/index.md
- docs/src/internals.md
- test/common.jl
- test/runtests.jl
> Modify recommended startup

- src/lowered.jl
- test/runtests.jl
It looks like Revise.jl can't handle baremodules as it is assuming `include` to exist in all modules.  This PR adds a simple fix and a test.
> Fix revising baremodules

- src/lowered.jl
- test/runtests.jl
> Handle methods defined with bad line info

- docs/src/config.md
- src/Revise.jl
Because the startup file loads before the REPL is available, we still need to wait for it to become available. Consequently I've kept the whole `wait_steal_repl_backend`, and made that do something different as appropriate. An advantage is that we don't need to tell folks to change their startup.jl files again.
Closes #423
CC @stevengj
> Use composable AST transform on Julia 1.5

- src/parsing.jl
- test/runtests.jl
Thanks for the nice reproducer, @KristofferC!
This also throws in another old commit I had failed to push, and a `test/Project.toml` file.
> Avoid BoundsError on incomplete parsing (fixes #448)

- .travis.yml
- Project.toml
- src/Revise.jl
- src/lowered.jl
- test/runtests.jl
https://github.com/JuliaLang/julia/pull/35138 changed line numbering in a good way, but we need to catch up.
> Fix line numbering on Julia master

- src/pkgs.jl
This can happen when Revise is put into a sysimage and it's dependencies are no longer in the Project/Manifest (as happens in https://github.com/JuliaLang/PackageCompiler.jl/issues/391)
> dont assume we can find source code for loaded packages

- src/pkgs.jl
This line threw an UndefVarError when I hit it, so I'm guessing this is just a simple typo fix.
> Fix up typo in filter_valid_cachefiles

- docs/src/dev_reference.md
- src/Revise.jl
- src/pkgs.jl
- src/precompile.jl
- src/types.jl
- test/runtests.jl
Instead of restarting new Tasks for file-watching, this introduces a loop. This seems a little easier to reason about, but this is mostly cosmetic. 
Inspired by investigating #459, but this does not fix it.
> Simplify Task structure

- src/Revise.jl
- src/pkgs.jl
- src/utils.jl
- test/runtests.jl
This fixes #459. It should also increase our test-coverage for the (atypical, except for FreeBSD) `watching_files[] = true` case.
> Don't stop file-watching with Ctrl-C

- src/precompile.jl
- src/relocatable_exprs.jl
- test/runtests.jl
This reduces the number of invalidation entries from 160 to 28 on Julia 1.6 (using custom branches of Julia & SnoopCompile).
> Small tweaks to reduce invalidations

- .travis.yml
- src/Revise.jl
- test/common.jl
- test/runtests.jl
Thanks to #488 the `entr` tests may finally be reliable on OSX. Let's run them and see what happens.
This also adds CI testing for `Revise.watching_files[] == true`, and of course fixes a couple of bugs (one that was lurking for a while, another that was a missing check in #488). CC @ffevotte, @tkluck.
Because OSX workers are in short supply and also quite slow, this also tests fewer Julia versions and skips the `Revise.watching_files[] == true` tests on OSX.
> Fix tests when watching files, run entr tests on OSX

- Project.toml
- src/Revise.jl
- src/lowered.jl
- src/pkgs.jl
- src/precompile.jl
- src/recipes.jl
- src/types.jl
- test/runtests.jl
This takes a multifaceted approach to resolving #431, which was a much trickier and problematic issue than a simple "not watching" warning might suggest. We were getting path corruption and duplication in the `pkgdatas` and other nasty issues stemming from race conditions among `track` and the handling of `@require`.
The key steps are:
- insert a new `pkgdata` into `pkgdatas` only when it is complete. This allows `add_require` to wait until the end of module initialization. Note this does not introduce any dependency on an actual lock.
- Have `track` bail if it's being called from `@require`. Since Revise 2.4, all `include` statements have been handled automatically, so this is redundant. This will issue a depwarn for all packages except Plots, for which I have a PR to fix it already …
> Handle order-dependent effects from asynchronous processes

- src/Revise.jl
- test/runtests.jl
Tests are modified so as to check that `entr`:
1. behaves well in cases of clustered events -> this is OK in the current master; it looks like incorrectly reported this as being a problem. Or perhaps it is only an issue when working with directories... At least we now have a way to check for this.
2. correctly removes user callbacks even when they throw -> this was indeed an issue ; a small fix is introduced in this PR.
Closes #494
(also related to #492)
> Fix #494 & improve `entr` tests

- src/Revise.jl
- src/pkgs.jl
- test/runtests.jl
This PR extends the work done in #492 to allow `entr` to watch directories. It is also re-based on the current `master`, in order to benefit from the latest bug fixes in `entr`.
At this stage, everything works in the case where `Revise.watching_files[] == false`. The tests performed for `entr` on directories mirror those defined for `entr` on files. In particular, they check that:
1. file creations, modifications and deletions in the directory are correctly detected;
1. clustered notifications trigger the callback only once;
1. empty directories are correctly handled (i.e. they remain in the watch list even when all files in them are deleted).
Upcoming commits should complete this PR to handle the case where `Revise.watching_files[]` is set.
> Allow `entr` to watch directories (fixes #470)

- docs/src/index.md
- src/Revise.jl
- test/runtests.jl
As requested in #469.
With this feature, `entr` and `add_callback`accept a new keyword argument `all`, which allows watching all files currently known to Revise, in addition to those specified in the regular positional arguments `files` and `modules`:
```
entr(f::Function, files, modules=nothing; all=false, postpone=false, pause=0.02)
add_callback(f, files, modules=nothing; all=false, key=gensym())
```
This change is not breaking since `all=false` by default.
TODO:
> Add an `all` kwarg to `entr` to watch all known files

- src/pkgs.jl
The regex based parsing will dissapear, instead use the
TOML functionality in Base. We could introduce a dependency
on the TOML stdlib but AFAIU that means we would need to
bump the compat of Revise to 1.6.
With this, most tests pass on https://github.com/JuliaLang/julia/pull/36018 and the ones that don't does not seem related to manifest tracking.
> fix for future changes in code loading

- src/recipes.jl
Without this change, I encountered the following while trying to test-revise part of Julia:
```
$ make test-revise-Mmap
JULIA test/revise-Mmap
ERROR: LoadError: no Revise.track recipe for module TOML
Stacktrace:
[1] error(::String, ::Symbol)
@ Base ./error.jl:42
...
```
I'm not sure if having `:TOML` added to the set conditional on the Julia version is what you want or not, so I can easily switch that to just a simple insert into the list if preferred.
> Add TOML to list of stdlibs for Julia v1.6

- src/Revise.jl
- test/runtests.jl
Hi!
Today I worked on a [highly requested Pluto feature](https://github.com/fonsp/Pluto.jl/issues/238): Revise support! Here is the [PR at Pluto](https://github.com/fonsp/Pluto.jl/pull/416/files#diff-446048a8133a25e0a07ba1f827fa93a2R37).
(It was surprisingly simple!) For this to work, I believe that we need a small change to Revise. 
_To explain why, some background on Pluto:_
Pluto uses `Distributed` to create notebook processes. The (HTTP) server has PID 1, notebooks are worker processes. These workers run independently from each other - they don't share code, loaded modules, package environments, etc., and if one notebook calls `using Revise`, then it is only loaded on that notebook's process. 
This is different from how Revise was designed to work inside Distributed, which is to load …
> Pluto support 🎈

- Project.toml
- docs/src/user_reference.md
- src/Revise.jl
- test/runtests.jl
After order-dependent errors, manually calling `revise()` wasn't adequate (what was I thinking??). `retry` fixes the problem nicely.
Feels weird to be releasing 3.1 so quickly, but it's a new feature, and I swear it wasn't me, semver made me do it mamma!
> Add `Revise.retry()`

- src/recipes.jl
- test/sigtest.jl
Stdlibs are breeding like rabbits these days!
Required for `make test-revise-*` to work.
> Add Downloads stdlibs and dependents

- Project.toml
- README.md
- src/pkgs.jl
- src/recipes.jl
- test/runtests.jl
- test/sigtest.jl
Hi, I'm having this issue. If I initialize julia in an empty environment (using `--project`) with and non-existent (yet) `Project.toml` file Revise complaint that it can not load the `Project.toml`
```julia
~ julia --project=.  
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
shell> ls Project.toml
ls: Project.toml: No such file or directory
julia> using Revise
ERROR: InitError: SystemError: opening file "/Users/Pereiro/Project.toml": No such file or directory
Stacktrace:
[1] #systemerror#43(::Nothing, ::Function, ::String, …
```
> Check for existing project_file

- Project.toml
~~Fixes~~Workaround for the breakage caused by Requires 1.1.0. See https://github.com/JuliaPackaging/Requires.jl/issues/94
> Add a fake Requires dependency and pin it at 1.0.x

- src/recipes.jl
- test/sigtest.jl
This is really getting out of hand... :grin:
> add Tar and ArgTools stdlibs

- src/lowered.jl
https://github.com/JuliaLang/julia/pull/37573 seems to have changed lowering:
```julia
julia> lwr = Meta.@lower begin
for T in (Int, Float64, String)
@eval mytypeof(x::$T) = $T
end
end
:($(Expr(:thunk, CodeInfo(
@ none:2 within `top-level scope'
1 ─ %1  = Core.tuple(Int, Float64, String)
│         #s192 = Base.iterate(%1)
│   %3  = #s192 === nothing
│   %4  = Base.not_int(%3)
└──       goto #4 if not %4
2 ┄ %6  = #s192
│         T = Core.getfield(%6, 1)
│   %8  = Core.getfield(%6, 2)
│  └
│   @ none:3 within `top-level scope'
│   %9  = Core._expr(:(::), :x, T)
│   %10 = Core._expr(:call, :mytypeof, %9)
│   %11 = Core._expr(:block, $(QuoteNode(:(#= none:3 =#))), T)
│   %12 = Core._expr(:(=), %10, %11)
│         Core.eval(Main, %12)
│         #s192 = Base.iterate(%1, %8)
│   %15 = #s192 === …
```
> handle `GlobalRef` case in `matches_eval`:

- Project.toml
I *think* this is the correct syntax for excluding only Requires-1.1.0. Testing locally seemed to work despite the lack of registration triggering at https://github.com/JuliaPackaging/Requires.jl/commit/4a23093e13208a4eec7e268802443d1712189cdd.
> Exclude only Requires version 1.1.0

- src/packagedef.jl
- test/runtests.jl
The problem here was that `add_callback()` calls `init_watching` with no
`pkgdata`, so the id of the files which are now watched by the callback
gets set unconditionally to NOPACKAGE. In turn, this breaks revision of
any of these files which were already being revised, because the id
check in `revise_dir_queued` fails and it no longer adds them to the
revision queue.
Instead, change init_watching to not update an existing id when pkgdata
== NOPACKAGE is supplied, unless we're not already watching the file.
This fixes #574.  I'm not sure it's the *best* way to fix it, but without providing a module to `add_callback` where the files will be `revise()`d within, it seems somewhat reasonable. I suppose the other option would be to default to `Main` like `Revise.track` does, but that might just …
> Fix revise() of non-package files with entr / add_callback

- Project.toml
- test/runtests.jl
#579 was fixed by https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/443, but we should test it here too.
This doesn't address #239, since any internal references to the name still refer to the old binding.
> Test fix for #579

- src/lowered.jl
- src/packagedef.jl
- src/precompile.jl
- src/relocatable_exprs.jl
Investigation via `SnoopCompile.@snoopi_deep` identified several
opportunities to reduce latency:
- https://github.com/JuliaLang/julia/pull/38906
- https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/461
- https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/58
Together with the changes here, the aggregate effect is to reduce
the time for the first revision from 3.1s
to about 1.5s. That's much more reasonable.
> Tweaks to reduce latency

- test/runtests.jl
- test/sigtest.jl
`redirect_std*` changed its implementation, and one of Revise's
tests indavertently depended on the former implementation.
Also load CodeTracking & LoweredCodeUtils via Revise for
the signatures test (facilitates `include("runtests.jl")` testing).
> Fix trivial test breakage on nightly

- src/types.jl
- test/runtests.jl
Fixes #596
The first revision will still be slow due to running the interpreter,
but the later ones will not repeat that work.
> Don't drop extra fields from FileInfo

- src/callbacks.jl
There can be cases where a callback key is removed from
`user_callbacks_by_key` but it still remains in `user_callbacks_queue`.
The problem may be illustrated with the following MRE.
Say, with the following diff
```diff
diff --git a/src/callbacks.jl b/src/callbacks.jl
index bff5256..865bb24 100644
--- a/src/callbacks.jl
+++ b/src/callbacks.jl
@@ -159,6 +159,7 @@ function entr(f::Function, files, modules=nothing; 
all=false, postpone=false, pa
sleep(pause)
f()
end
+    @info "added $(key)"
try
while true
wait(revision_event)
@@ -168,7 +169,7 @@ function entr(f::Function, files, modules=nothing; 
all=false, postpone=false, pa
isa(err, InterruptException) || rethrow(err)
finally
remove_callback(key)
+        @info "removed $(key)"
end
nothing
end
-
```
and we run the following script:
> …
> remove callback key from `user_callbacks_queue` in `remove_callback!`

- src/packagedef.jl
Fixes #601
No test :frowning: , but the effort to test it just doesn't seem worth it in this case.
> Add a warning if juliadir does not exist

- src/pkgs.jl
A new Manifest.toml format is coming in 1.7 with support in 1.6.2
https://github.com/JuliaLang/julia/pull/40765
https://github.com/JuliaLang/Pkg.jl/pull/2561
https://github.com/JuliaLang/Pkg.jl/pull/2580
This is intended to work for both old and new formats
> Handle new Manifest.toml format

- src/packagedef.jl
- test/runtests.jl
When evaluation of one module throws an error, evaluation of another
might fix it. This tries again until we stop making progress.
Fixes #627
> Allow evaluation of later modules on err

- src/lowered.jl
With the `@nospecialize` added, the result is no longer inferrable.
> Type-assert the result of `predicate(stmt)`

- src/packagedef.jl
- src/precompile.jl
Fixes https://github.com/timholy/Revise.jl/issues/549
Slightly rework the latency hiding mechanism to no longer be dependent on having the `package_callbacks` fire just after the Revise `__init__` method runs.
Note, I have not done significant latency testing with this.
> allow Revise to work when put into a sysimage

- .github/workflows/ci.yml
- .gitignore
- src/packagedef.jl
- src/pkgs.jl
- test/envs/use_exputils/install.jl
- test/envs/use_exputils/setup.sh
- test/envs/use_exputils/switch_version.jl
Fixes #647
Fixes #645 
Fixes #617
This also allows one to switch among package versions more reliably. Good support for changing environments will require https://github.com/JuliaLang/Pkg.jl/pull/2744.
> Stop pushing results to backend.response_channel

- docs/src/index.md
Fix homepage warning admonition:
Signed-off-by: ErikQQY <2283984853@qq.com>
> Fix warning admonition in home page

- docs/src/config.md
Reading through `config.md`, I noticed minor grammar mistake in the following paragraph:
> Unfortunately, a few file systems systems (notably, the Unix-based Network File System NFS) don't support this approach. In such cases, Revise needs to "actively" check each file periodically to see whether it has changed since the last check. This active process is called polling. You turn on polling by setting the environment variable JULIA_REVISE_POLL to the string "1" (e.g., JULIA_REVISE_POLL=1 in a bash script).
Notice the double usage of **systems** in the first sentence. Pull request changes the paragraph to the following:
> Unfortunately, a few file systems (notably, the Unix-based Network File System NFS) don't support this approach. In such cases, Revise needs to "actively" check each file …
> Fix minor grammatical error in config.md

- test/runtests.jl
This functionality won't be available on 1.8 since it seems like
a package can't be loaded at all when its precompilation failed
because of a broken dependency in v1.8 and higher.
> don't run `Broken dependencies` test on 1.8

- src/lowered.jl
- test/runtests.jl
> Support module-style 2-argument includes

- src/packagedef.jl
- test/runtests.jl
Fix https://github.com/timholy/Revise.jl/issues/689.
Shouldn't all `PkgId(mod)` be mapped to `PkgId(mod, string(mod)` (else `PkgId(mod)` maps to `PkgId(mod, "Main")`) ?
> fix `includet` using `mod` argument

- .github/workflows/ci.yml
- src/loading.jl
- src/packagedef.jl
- test/juliadir.jl
`parentfile` is inconsistent with `filedata`: on a local build of julia, where `juliadir` points to `basebuilddir`, `parentfile` returns a path starting with `Sys.BINDIR/Base.DATAROOTDIR` because of `Base.find_source_file`.
This is not consistent with `filedata` (`Base._included_files`) which point to files in `basebuilddir`.
- fix https://github.com/timholy/Revise.jl/issues/697;
- add a specific ci test using a forced `juliadir` path (`test/juliadir.jl`).
- update `ci.yaml`, use `@latest` if possible, rewrite some parts for clarity;
- use `julia-actions/cache@v1`;
> fix `parentfile`

- src/utils.jl
As far as I can tell, this has the exact same functionality but allows Base.Libc to move to `timespec` internally (and get rid of deprecated unix functionality). Ref https://github.com/JuliaLang/julia/pull/45023. Shouldn't break anything, as this is internal, right?
> Remove dependency on `Libc.TimeVal` by directly calling `time()` instead

- docs/src/internals.md
An alternative link is http://web.archive.org/web/20200722031736/https://linuxacademy.com/blog/linux/introduction-using-diff-and-patch/
..but that loads a bit slower
> docs: update dead link

- src/packagedef.jl
Fixes #719 (speeds up loading Revise from 1.2 to 0.2 seconds when loading from startup.jl)
```
$ ./julia
using Revise: 0.225344 seconds (556.59 k allocations: 36.000 MiB)
_
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.10.0-DEV.215 (2022-12-28)
_/ |\__'_|_|_|\__'_|  |  Commit 82fbf54131 (0 days old master)
|__/                   |
julia> includet("test.jl")
julia> foo(1)
1
#edit foo in file
julia> foo(1)
2
```
> Wait for repl async to allow for startup.jl loading sequence

- test/runtests.jl
#710 attempted to debug a Requires-based hang that seems
to only occur on CI with Julia 1.8. It may be due to lock contention,
but the precise cause was not obvious.
This just disables the problematic test.
Since it doesn't happen on nightly, and since Requires will be
supplanted by the new weakdeps mechanism, we can direct any
users who encounter this bug to the alternatives.
> Circumvent CI hang on 1.8

- Project.toml
- src/packagedef.jl
Loading a package like StaticArrays invalidates
much of Revise's code. This protects it by using
runtime-dispatch for the invalidating calls.
Exploits https://github.com/timholy/CodeTracking.jl/pull/101
> Insulate Revise methods from invalidation

- .github/workflows/ci.yml
Currently CI errors (only on Julia nightly) with `UNHANDLED TASK ERROR: IOError: stream is closed or unusable`. 
I can't replicate this error locally, so it's not easy to debug.
> Add more logging for "stream is closed or unusable"

- src/packagedef.jl
This invalidation was triggered by
```julia
convert(::Type{T}, i::LoopVectorization.UpperBoundedInteger) where T<:Number
```
It turns out `eval_rex` had a `Core.Box` and various issues stemming from
too many small Unions for inference to succeed. Some of the later calls
imply that the type must be specific (there are no methods that can
handle the alternative type). By type-asserting that type early we avoid
the inference failures.
Now that the first `revise` is typically very fast on Julia 1.9, these invalidations
are very noticeable because of the (now-surprising) lag they cause.
> Fix invalidation in `eval_rex`

- src/packagedef.jl
This might be a very bad idea. Tries to fix #728
> Do not track files during pre-compilation

- src/packagedef.jl
After JuliaLang/julia#48766, `typemax(UInt)` is no longer valid argument for the `Base._methods_by_ftype` query.
> make Revise compatible with the latest nightly

- test/common.jl
Use the documented `default_rng` instead of the internal GLOBAL_RNG.
Julia's testsets will automatically restore the state of the global RNG to improve tests' reproducibility. This is a problem for Revise, that needs actual random directories.
Previous code would mutate the global RNG to keep it from being restored. This code instead uses a local RNG object.
> Simplify RNG used for making temp dirs

- src/packagedef.jl
Just noticed that `Revise.track(PkgA, "src/PkgA.jl")` fails on Revise@3.5.2:
```julia
julia> using JET
julia> using Revise
julia> Revise.track(JET, normpath(pkgdir(JET), "src/JET.jl"))
julia> JET.hello()
┌ Warning: /Users/aviatesk/julia/packages/JET/src/JET.jl/ no longer exists, deleted all methods
└ @ Revise ~/julia/packages/Revise/src/packagedef.jl:668
ERROR: UndefVarError: `hello` not defined
Stacktrace:
[1] top-level scope
@ REPL[4]:1
```
The issue here seems to be that `file` passed to `handle_deletions` can be `"."`, causing https://github.com/timholy/Revise.jl/blob/eb0bd3ff9c353191eb2c6af2f56194616bce471c/src/packagedef.jl#L654 to return invalid file path.
This commit aims to fix it by adding a special case for the `file == "."` case in `handle_deletions`.
> fix `Revise.track(PkgA, "src/PkgA.jl")`

- Project.toml
- src/pkgs.jl
- test/runtests.jl
Otherwise Revise doesn't detect when having switched environments.
MWE:
```julia
using Revise
using Pkg
Pkg.activate(; temp=true)
Pkg.add(url="https://github.com/maleadt/ReviseTest.jl",
rev="cf766c822806398f4ac8e89fb7b588d551e70d1f")
using ReviseTest
@show ReviseTest.test()
Pkg.add(url="https://github.com/maleadt/ReviseTest.jl",
rev="6396547c3871f07830744267391cfba5146eba12")
Revise.revise()
@show ReviseTest.test()
```
The first revision has `test() = 1`, the second one `test() = 2`. Currently, Revise  only has a manifest watcher for the main environment Revise was imported in, i.e., not the temporary one that contains the ReviseTest package. By adding a new watcher when we receive the package callback hook when importing ReviseTest, we detect changes to the temporary manifest and …
> When receiving a package callback, start watching the current environment.

- src/packagedef.jl
Otherwise REPL will result in the following error since `isempty` is resolved within `Core.Compiler` context module:
```julia
Core.Compiler) julia> 42
ERROR: MethodError: no method matching iterate(::Base.Set{Tuple{Revise.PkgData, String}})
You may have intended to import Base.iterate
Closest candidates are:
iterate(::MethodSpecializations)
@ Core reflection.jl:1146
iterate(::MethodSpecializations, ::Nothing)
@ Core reflection.jl:1152
iterate(::MethodSpecializations, ::Int64)
@ Core reflection.jl:1153
...
Stacktrace:
[1] isempty(itr::Base.Set{Tuple{Revise.PkgData, String}})
@ Core.Compiler ./essentials.jl:952
[2] top-level scope
@ none:1
```
> make REPL AST transform work when `active_module` is set to `Core.Compiler`

- src/packagedef.jl
The default behaviour is to skip recursively included files for tracking. This is now correctly mirrored in the doctring
> Correct default use of `skip_include` in `includet` docstring

- src/pkgs.jl
Since `manifest_file()` can return `nothing` as well, add a check/guard for when it's `nothing` in `active_project_watcher`.
Fixes #762.
> fix: add check for `nothing` as manifest file in active_project_watcher

- docs/Project.toml
- docs/src/cookbook.md
- docs/src/dev_reference.md
- docs/src/index.md
- docs/src/user_reference.md
This gives many nice convenience features like, e.g., a better search, a GitHub link to the repo at the top of the docs, collapsable docstrings and many more. I only had to fix a few mistakes in the docs (which under v1 lead to errors instead of warnings), like a few dead links etc.
Tested locally, let's see what CI says.
> Update to Documenter v1

- src/loading.jl
`Base.parse_cache_headers` removed its keyword `srcfiles_only` in https://github.com/JuliaLang/julia/pull/49866, which makes Revise non-functional in nightly.
There are a bunch of other test failures, and I'm not sure I understand the internals enough to address them, but I could identify least two sources (there are probably more):
- `LoadError` seems to now (sometimes?) hold a `Meta.ParseError` value for its `.error` field, breaking a few tests which expect a `String` instead. A bunch of related error messages seem to have changed too.
- Source files can't be located for `Pkg` (the associated `(::PkgData).info.files` is empty, probably that's because of that), breaking related tests.
Anyway, we can probably merge this fix and worry about other failures on `nightly` later, such that …
> Fix `parse_cache_header` signature change

- Project.toml
- src/utils.jl
- test/runtests.jl
Revise extracts the documented expression and puts that before the full
doc expression in the revision queue. E.g. in `"docs" f(x) = x` there
will be a revision of `f(x) = x` followed by a revision of the full
expresion (`"docs" f(x) = x`). However, in many cases a docstring is
only attached to a signature (not a function body/struct definition,
etc.) and in this case the revision of the signature is not needed.
Revise already filters out the base case, `"docs" f(x)`. This patch
extends this filtering to also apply to `where`-clauses such as e.g.
`"docs" f(x::T) where T <: Integer`.
Concretely, this patch fixes #735, i.e. revising doc expressions where
the signature doesn't lower without the context of the doc macro. As a
bonus, slightly less work has to be done for e.g. `"docs" f(x::T) …
> Filter out more doc signature expressions

- Project.toml
- src/loading.jl
This patch restores the filtering of non-src files that was lost
in https://github.com/timholy/Revise.jl/pull/767. After https://github.com/JuliaLang/julia/pull/49866,
`Base.parse_cache_header` returns both the non-filtered and filtered
list instead of doing filtering internally based on the
`srcfiles_only::Bool` keyword argument.
There is a test for this failure mode that fails on Revise master branch
and passes with this patch (see
https://github.com/timholy/Revise.jl/blob/1059181bed06387e9fbcea137dce28a80c5c45d9/test/runtests.jl#L3070-L3080).
> Restore filtering of non-src files

- src/Revise.jl
- src/packagedef.jl
- src/utils.jl
Since the minimum version compat for Revise is now 1.6, we can expect `GotoIfNot` to be defined within `Core` always.
> minor updates on old code

- .github/workflows/ci.yml
There are two ways of doing this, another possibility is to have a separate `ci_nightly.yml`, let me know if maintainers prefer that route.
> allow CI nightly to fail so badge is green

- test/common.jl
- test/populate_compiled.jl
- test/runtests.jl
- test/sigtest.jl
In particular, the new parser generates different (and much better) error messages; we were testing the content of the error message, so that has to change.
Also skips a portion of the old signature tests due to usage of `include(mapexpr, file)`, which is not (and may never be) supported by Revise.
> Fix tests that were broken by 1.10

- src/lowered.jl
- test/runtests.jl
Setting `pc=nothing` is premature at this stage.
Together with https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/91, this fixes #758.
This will fail the new test because I haven't tagged a new release of LoweredCodeUtils. However, that's a bit unsafe to release without this change---it will trigger this bug more often than it used to. So I'll let this test fail, merge & make a new Revise release, and then release LoweredCodeUtils.
> Correct pc for empty function definition

- src/lowered.jl
An error in `sigtest` was triggered by an anonymous-function thunk being executed twice ("invalid redefinition..."). This ensures synchrony between the local variable `pc` and `frame.pc` and prevents double-execution.
> Prevent double-execution of thunks

- test/non_jl_test.jl
It is failing frequently on Mac, which performs poorly in file-watching without delays.
> Add filesystem delays in non_jl_test.jl

- src/lowered.jl
- src/precompile.jl
- test/backedges.jl
When a single top-level expression contains both `const` definitions and methods that use those consts, the `add_named_dependencies!` step of `lines_required!` can induce a dependency on the statement assigning to the `const`. This is problematic when your only goal is to parse signatures, as it can trigger overwriting of `consts` that may be needed.
Fixes #789
> Reduced reassignment to global consts

- .github/workflows/ci.yml
- src/parsing.jl
- test/runtests.jl
Now that sufficient line information is incorporated into the
error-expressions returned by parsing, we can eliminate our
old hack to try to find some identifying information.
(Thanks, @c42f!)
Fixes #655
> Let Base handle parsing errors on Julia 1.10+

- src/lowered.jl
- test/backedges.jl
- test/runtests.jl
> Eval thunks that create methods

- src/lowered.jl
- src/parsing.jl
- test/runtests.jl
This adds a test for #718, and makes a change to Revise's parsing that will be necessary for the true fix, which will happen in JuliaInterpreter. Unfortunately this needs to be merged and tagged before that is safe to release. So the new test will fail, but I think we can live with that transiently.
> Groundwork for a fix for #718

- docs/src/limitations.md
Fix https://github.com/timholy/Revise.jl/issues/797
See Discourse thread:
https://discourse.julialang.org/t/revise-not-updating-functions/108391/12
Basically we replace the initial struct changing session with the following.
1. Use an abstract parent type for all struct versions and method definitions
2. Provide a full blown REPL session and example showing all steps
3. Explicitly use `write` to demonstrate editing steps.
4. Follow through with a Julia session restart
5. Demonstrate `isconst` on `FooStruct`.
> Update limitations.md with REPL session

- src/pkgs.jl
Fixes https://github.com/timholy/Revise.jl/issues/802
> Workaround issue when internal code loading function gives a path to entry file instead of directory to package

- src/pkgs.jl
`Base.explicit_manifest_entry_path()` can return either a String, `missing`, or `nothing`, but previously `manifest_paths!()` was assuming the result was either a String or `nothing`.
Here's the stacktrace from when it failed for me:
```julia
julia> ┌ Error: Error watching manifest                                                                                                                                                                                                        
│   exception =                                                                                                                                                                                                                                
│    MethodError: no method matching joinpath(::Missing) …
```
> Explicitly check if manifest paths are Strings

- .github/workflows/ci.yml
https://github.com/timholy/Revise.jl/pull/800 broke codecov (see https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857). To fix it @timholy you need to add a token named CODECOV_TOKEN to the repo.
> fix codecov

- test/runtests.jl
Almost all the real work of updating to 1.11 was in https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/108 and https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/109. But a warning now prints with different text, so accept both variants.
> Fix tests broken on 1.11

- .github/workflows/ci.yml
- Project.toml
- src/lowered.jl
- src/parsing.jl
- src/utils.jl
Companion PR to https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/107. With both of these and https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/634, basic Revise functionality is working for me again on Julia master.
> Track `GlobalRef` consistently

- Project.toml
- src/packagedef.jl
The only use (`Pkg.Types.active_project_watcher_thunks`) never existed.
Ref https://github.com/JuliaLang/Pkg.jl/pull/2744.
> remove Pkg as a dependency

- .github/workflows/ci.yml
- Project.toml
- src/loading.jl
- src/lowered.jl
- src/packagedef.jl
- src/pkgs.jl
- src/utils.jl
- test/runtests.jl
- test/start_late.jl
With this and the LCU fixes, Revise should pass tests again on 1.12.
> More 1.12 compat

- src/loading.jl
The base commit got backported in rc. Should fix #832.
> Extend loaded_precompiles fix to 1.11

- test/runtests.jl
Try to fix #834. Will confirm on buildkite.
> do a little bit of work to try confirm that the git repo found is actually a julia repo before running `Core.Compiler` test

- test/runtests.jl
This makes reading test logs slightly less noisy, scary and confusing.
> Capture log message instead of telling users to ignore it

- Project.toml
- src/packagedef.jl
Fixes #839
Fixes #842
@staticfloat and/or @danielalcalde can you test whether this works for you? The behavior I think you're wanting is now `revise(mod; force=false)`.
> Add `force=true` kwarg to `revise(mod::Module)`

- src/packagedef.jl
- src/recipes.jl
Fixes #845
@frankier, can you test whether this works for you? I'm guessing it's not straightforward to reliably test this.
> Add locking to `revise()`

- test/sigtest.jl
On Windows, Julia 1.6, the signatures test fails with
```
Base signatures: Error During Test at D:\a\Revise.jl\Revise.jl\test\runtests.jl:3851
Got exception outside of a @test
LoadError: invalid redefinition of constant RandomDevice
Stacktrace:
[1] do_assignment!(frame::Frame, lhs::Any, rhs::Any)
@ JuliaInterpreter C:\Users\runneradmin\.julia\packages\JuliaInterpreter\cxlKp\src\interpret.jl:352
in expression starting at D:\a\Revise.jl\Revise.jl\test\sigtest.jl:106
```
Since this only happens on a soon-to-be-unsupported Julia release, let's just ignore the test.
> Skip a problematic test on 1.6

- src/packagedef.jl
> Clarify docstring for `includet`

- src/loading.jl
I added an explicit accessor for this in
https://github.com/JuliaLang/julia/pull/55963
so Revise doesn't have to rely on internals.
> Stop using `eval` to find module location

- src/lowered.jl
Prepares for https://github.com/JuliaLang/julia/pull/55949.
> Prepare for upcoming change to `include`

- src/packagedef.jl
- test/runtests.jl
The `linfo` field of `StackFrame` can now be a `CodeInstance`.
> Adjust to https://github.com/JuliaLang/julia/pull/56878

- .github/workflows/ci.yml
- Project.toml
- ext/DistributedExt.jl
- src/packagedef.jl
- src/parsing.jl
This moves support for Distributed into a package extension and adds an interface for other distributed worker libraries (i.e. DistributedNext.jl) to use to support Revise for their workers. Admittedly the interface is quite... clunky... so I'm open to other ideas. This also required bumping the minimum Julia version to 1.9 to use package extensions.
As a bonus the load times are slightly improved:
```julia-repl
julia> @time_imports using Revise
2.7 ms  OrderedCollections
0.2 ms  UUIDs
3.8 ms  CodeTracking
┌ 0.2 ms JuliaInterpreter.__init__() 
136.9 ms  JuliaInterpreter 72.95% compilation time
35.6 ms  LoweredCodeUtils
0.7 ms  Serialization
┌ 0.0 ms Distributed.__init__() 
31.7 ms  Distributed 71.09% compilation time
┌ 0.0 ms NetworkOptions.__init__() 
2.2 ms  NetworkOptions
0.4 ms …
```
> Implement an interface for Distributed-like libraries

- test/runtests.jl
Fixes https://github.com/timholy/Revise.jl/issues/872
> Tests: Remove faulty registry install skip given registry install is fast now

- src/packagedef.jl
This is to ensure that the functions can be called from an older world if the package extension was loaded in a newer world.
Maybe fixes #880.
> Call distributed worker functions with `@invokelatest`

- src/pkgs.jl
- test/runtests.jl
- test/sigtest.jl
- test/switch_version.jl
With struct replacement enabled, the state of the process after the sigtest is somewhat problematic (e.g. references to IOContext will get the new world). Move it to a separate process and try to avoid world age increments so that this doesn't cause problems.
> Make sigtest more robust

- src/Revise.jl
- src/lowered.jl
- test/runtests.jl
This variable is always `true` on recent versions
> remove `CodeTracking.line_is_decl` usages

- src/precompile.jl
With only using Revise in the startup.jl and this commit, there are two precompiles less with
`julia --trace-compile=stderr -ie "exit()"`
This partially addresses #900.
> Get rid of two precompiles from trivial Julia execution

- Project.toml
- docs/.gitattributes
- docs/.gitignore
- docs/Manifest.toml
- src/Revise.jl
- src/lowered.jl
- src/packagedef.jl
- src/precompile.jl
- test/runtests.jl
This commit implements the migration to the new JuliaInterpreter
interface proposed in https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/683.
It purely performs the migration to the new interface and does not
include any refactoring based on it.
In practice, `methods_by_execution!` is quite complex, and using the
`Interpreter` interface may not allow us to simplify its implementation.
That said, this commit seems to achieve a modest latency improvement by
changing the argument type declaration from `@nospecialize(recurse)` to
`interp::Interpreter` (with easier code specialization).
> update to JuliaInterpreter 0.10

- src/lowered.jl
- src/packagedef.jl
- src/types.jl
- test/backedges.jl
This data structure was added in 32f8727b4859f114b14ab00ab30ecaa3a84da37a, but its functionality has since been provided by LoweredCodeUtils and is no longer needed. This removes all code related to `moduledeps` and clean up.
> remove no-longer necessary `moduledeps` data structure

- Project.toml
- docs/src/dev_reference.md
- src/callbacks.jl
- src/packagedef.jl
- src/parsing.jl
- src/pkgs.jl
- src/recipes.jl
- src/relocatable_exprs.jl
- src/types.jl
- src/utils.jl
- test/non_jl_test.jl
- test/runtests.jl
The interface added in timholy/Revise.jl#680 for supporting non-.jl files assumes usages of custom struct, which requires overloading functions like `abspath` and is therefore quite cumbersome. Worse still, that makes it harder to refactor Revise code base, since now we need to think about the possibility of arbitrary types in places that originally needed to handle `AbstractString`.
This commit provides a simpler interface: support custom files by registering parsers per file extension in
`Revise.parsers::Dict{String,Any}`.
The greatly simplified `non_jl_test.jl` demonstrates how much more straightforward this approach is.
Of course, a potential downside is that if multiple packages register different parsers for the same extension, conflicts could arise, but since this feature is …
> remove the interface to support non .jl files

- src/recipes.jl
It shares a UUID with the Compiler stdlib (which depending on version may or may not delegate to Core.Compiler). I think this should work because in the non-delegation case, the Compiler stdlib doesn't actually load any files and in the delegation files they are totally separate, but let's keep an eye on any Revise weirdness around the Compilers.
Fixes #935
> Track Core.Compiler under a separate PkgId

- src/pkgs.jl
- test/runtests.jl
This adds a test (EDIT: and fix!) of #858
Fixes #858
To anyone reviewing: what if the extension isn't there under the new path? I lean towards thinking we should switch anyway and let the method-deletion happen, but I welcome other thoughts.
> Path-switching for extensions

- src/packagedef.jl
Recent versions of Julia have changed the expression to
```
julia> 1+1
:($(Expr(:toplevel, :(#= REPL[5]:1 =#), quote
$(Expr(:softscope, true))
1 + 1
end)))
2
```
Fixes #887
> Improve the exit-check

- src/recipes.jl
Fixes
```
% ./julia -E 'using Revise; Revise.track(Base); Base.Threads.foo()' 
ERROR: UndefVarError: `foo` not defined in `Base.Threads`
```
PR
```
% ./julia -E 'using Revise; Revise.track(Base); Base.Threads.foo()'
1
```
> Force revise() after Revise.track
